#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

# General settings
if [[ ! -d /tmp ]]; then
        mkdir /tmp
fi

chmod 777 /tmp

########################################
# Installation                         #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1
curl -fsSL https://deb.nodesource.com/setup_22.x | sudo bash - &&\
sudo apt-get install -y nodejs

npm install -g pnpm
if ! which pnpm &> /dev/null; then
        echo "pnpm not found after sourcing"
        exit 1
fi

npm install -g npm@11.5.1

popd &> /dev/null || exit 1
