#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

# General settings
readonly REPO="https://gitlab.com/dfu-util/dfu-util.git"
readonly BRANCH="master"
readonly DEPS=(git libusb-1.0-0-dev autoconf pandoc)

########################################
# Install System Packages              #
########################################

apt-get install --yes "${DEPS[@]}"

########################################
# Clone Repository                     #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1
sudo -u "${BASE_USER}" git clone "${REPO}" dfu-util -b "${BRANCH}"
popd &> /dev/null || exit 1

########################################
# Build config and install             #
########################################

pushd "/home/${BASE_USER}/dfu-util" &> /dev/null || exit 1

# Create config file
./autogen.sh
./configure

# Run install script
make install

popd &> /dev/null || exit 1

########################################
# Remove Build Dependencies            #
########################################

apt-get purge --yes pandoc
